### ISSUE TITLE
Access Denied. What I'm doing wrong?

### ISSUE THREAD

**Issue by gustavo-almeida** [automatictester/lightning#25]
I'm trying to read the CSV, but in both locals (Teamcity and my machine) I'm receiving this error:

command:
java -jar c:\lighting\lightning-0.6.0.jar report -csv=c:\JMeterLogs\

error:
Exception in thread "main" uk.co.automatictester.lightning.exceptions.CSVFileIOException: W:\Teamcity\apache-jmeter-2.13\bin (Access is denied)
at uk.co.automatictester.lightning.readers.JMeterCSVFileReader.getTransactions(JMeterCSVFileReader.java:41)
at uk.co.automatictester.lightning.TestRunner.runReport(TestRunner.java:65)
at uk.co.automatictester.lightning.TestRunner.main(TestRunner.java:33)

**Comment by gustavo-almeida** [comment]
Forget about it.. the path was incomplete.

java -jar c:\lighting\lightning-0.6.0.jar report -csv=c:\JMeterLogs\resultado2.csv
